# Generated by Django 6.0 on 2026-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0001_initial'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipments',
            field=models.ManyToManyField(to='expedition.shipment'),
        ),
    ]
