# Generated by Django 6.0.1 on 2026-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('logistics', '0002_driver_servicetype_vehicle_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipments',
            field=models.ManyToManyField(to='logistics.shipment'),
        ),
    ]
