# Generated by Django 6.0 on 2026-01-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipments',
            field=models.ManyToManyField(to='logistics.shipment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.invoice'),
        ),
    ]
