# Generated by Django 5.2.10 on 2026-01-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_alter_invoice_amount_ht_alter_invoice_amount_ttc_and_more'),
        ('facturation', '0002_alter_invoice_shipments'),
    ]

    operations = [
    ]
