# Generated by Django 5.2.10 on 2026-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_merge_20260124_1328'),
        ('logistics', '0005_driver_zone_typeservice_volume_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipments',
            field=models.ManyToManyField(to='logistics.shipment'),
        ),
    ]
