# Generated by Django 5.2.10 on 2026-01-24 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0005_driver_zone_typeservice_volume_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('tour_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de tournée')),
                ('starting_hour', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('finishing_hour', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('kilometers', models.FloatField(blank=True, default=0, null=True, verbose_name='Kilométrage')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée')),
                ('fuel_consumption', models.FloatField(blank=True, default=0, null=True, verbose_name='Consommation carburant (L)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=30, verbose_name='Statut')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('has_delay', models.BooleanField(default=False, verbose_name='Retard')),
                ('delay_minutes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Minutes de retard')),
                ('has_technical_issue', models.BooleanField(default=False, verbose_name='Problème technique')),
                ('technical_issue_description', models.TextField(blank=True, null=True, verbose_name='Description du problème')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='logistics.driver', verbose_name='Chauffeur')),
                ('id_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='logistics.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
                'ordering': ['-tour_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre de livraison')),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_assignments', to='logistics.shipment')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_expeditions', to='tour.tour')),
            ],
            options={
                'verbose_name': 'Expédition de tournée',
                'verbose_name_plural': 'Expéditions de tournée',
                'ordering': ['order'],
                'unique_together': {('tour', 'expedition')},
            },
        ),
    ]
