# Generated by Django 5.2.10 on 2026-01-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0003_remove_tour_id_driver_remove_tour_id_vehicle_and_more'),
        ('incidents', '0001_initial'),
        ('logistics', '0002_chauffeur_vehicule_remove_tour_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='expedition.shipment', verbose_name='Expédition'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logistics.tournee', verbose_name='Tournée'),
        ),
    ]
