# Generated by Django 5.2.10 on 2026-01-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_shipment_alter_incident_tour'),
        ('logistics', '0005_driver_zone_typeservice_volume_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logistics.shipment', verbose_name='Expédition'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='logistics.tour', verbose_name='Tournée'),
        ),
    ]
