# Generated by Django 6.0 on 2026-01-23 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery_date', models.DateField()),
                ('reel_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Créée'), ('PENDING', 'En attente'), ('IN_TRANSIT', 'En transit'), ('DELIVERED', 'Livrée'), ('FAILED', 'Échec')], default='CREATED', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to=settings.AUTH_USER_MODEL)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.destination')),
                ('id_service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('tour_date', models.DateField()),
                ('starting_hour', models.TimeField()),
                ('finishing_hour', models.TimeField()),
                ('kilometers', models.FloatField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.driver')),
            ],
        ),
    ]
