# Generated by Django 5.2.10 on 2026-01-23 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_address_alter_client_code_client_and_more'),
        ('expedition', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.destination'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.typeservice'),
        ),
        migrations.AddField(
            model_name='tour',
            name='id_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.chauffeur'),
        ),
        migrations.AddField(
            model_name='tour',
            name='id_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicule'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedition.tour'),
        ),
        migrations.AddField(
            model_name='tourshipment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedition.shipment'),
        ),
        migrations.AddField(
            model_name='tourshipment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedition.tour'),
        ),
    ]
