# Generated by Django 6.0 on 2026-01-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedition', '0001_initial'),
        ('logistics', '0002_chauffeur_vehicule_remove_tour_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='id_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicule'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedition.tour'),
        ),
        migrations.AddField(
            model_name='tourshipment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedition.shipment'),
        ),
        migrations.AddField(
            model_name='tourshipment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedition.tour'),
        ),
    ]
