# Generated by Django 5.2.10 on 2026-01-24 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('expedition', '0002_initial'),
        ('logistics', '0002_chauffeur_vehicule_remove_tour_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='id_driver',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='id_vehicle',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.tournee'),
        ),
        migrations.RemoveField(
            model_name='tourshipment',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourshipment',
            name='shipment',
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'Expédition', 'verbose_name_plural': 'Expéditions'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.destination'),
        ),
    ]
