# Generated by Django 6.0.1 on 2026-01-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0002_initial'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourshipment',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='id_driver',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='id_vehicle',
        ),
        migrations.RemoveField(
            model_name='tourshipment',
            name='tour',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourShipment',
        ),
    ]
