# Generated by Django 5.2.10 on 2026-01-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0003_remove_tour_id_driver_remove_tour_id_vehicle_and_more'),
        ('logistics', '0003_typeservice_delete_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.typeservice'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourShipment',
        ),
    ]
