# Generated by Django 5.2.10 on 2026-01-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0004_alter_shipment_id_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='id_destination',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='id_service_type',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='id_tour',
        ),
    ]
