# Generated by Django 5.2.10 on 2026-01-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0005_remove_shipment_created_by_remove_shipment_id_client_and_more'),
        ('facturation', '0004_alter_invoice_shipments'),
        ('incidents', '0003_alter_incident_shipment_alter_incident_tour'),
        ('reclamation', '0003_alter_reclamation_shipments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
