# Generated by Django 6.0.1 on 2026-01-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_address_alter_client_code_client_and_more'),
        ('expedition', '0003_remove_tourshipment_shipment_remove_tour_id_driver_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity', models.FloatField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournee',
            name='chauffeur',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='client',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='tournee',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='type_service',
        ),
        migrations.RemoveField(
            model_name='tournee',
            name='vehicule',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='pays',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='ville',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='code_postal',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='adresse',
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField()),
                ('starting_hour', models.TimeField()),
                ('finishing_hour', models.TimeField()),
                ('kilometers', models.FloatField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery_date', models.DateField()),
                ('real_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.destination')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.servicetype')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.tour')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='zone',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='logistics.zone'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chauffeur',
        ),
        migrations.DeleteModel(
            name='Expedition',
        ),
        migrations.DeleteModel(
            name='TypeService',
        ),
        migrations.DeleteModel(
            name='Tournee',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
