# Generated by Django 6.0 on 2026-01-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.destination'),
        ),
        migrations.AddField(
            model_name='tour',
            name='id_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.tour'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.chauffeur'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.typeservice'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicule'),
        ),
        migrations.AddField(
            model_name='tour',
            name='id_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicule'),
        ),
        migrations.AddField(
            model_name='destination',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.zone'),
        ),
    ]
