# Generated by Django 6.0 on 2026-01-23 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_alter_invoice_shipments'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='vehicle',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='city',
            new_name='pays',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='country',
            new_name='ville',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='volume_rate',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='weight_rate',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='adresse',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='code_postal',
            field=models.CharField(default='Unknown postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_driver',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, unique=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='nom',
            field=models.CharField(default='Standard Service', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='nom',
            field=models.CharField(default='Unknown zone', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicule')),
            ],
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
