# Generated by Django 5.2.10 on 2026-01-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0003_remove_tour_id_driver_remove_tour_id_vehicle_and_more'),
        ('logistics', '0002_chauffeur_vehicule_remove_tour_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
