# Generated by Django 5.2.10 on 2026-01-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0004_alter_shipment_id_service_type_and_more'),
        ('logistics', '0003_typeservice_delete_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.AlterField(
            model_name='destination',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='code_postal',
            field=models.CharField(max_length=20),
        ),
    ]
