# Generated by Django 5.2.10 on 2026-01-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('logistics', '0004_delete_servicetype_delete_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='typeservice',
            name='volume_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='weight_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('tour_date', models.DateField(blank=True, null=True)),
                ('starting_hour', models.TimeField(blank=True, null=True)),
                ('finishing_hour', models.TimeField(blank=True, null=True)),
                ('kilometers', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('id_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.driver')),
                ('id_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('reel_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Créée'), ('PENDING', 'En attente'), ('IN_TRANSIT', 'En transit'), ('DELIVERED', 'Livrée'), ('FAILED', 'Échec')], default='CREATED', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to=settings.AUTH_USER_MODEL)),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('id_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.destination')),
                ('id_service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.typeservice')),
                ('id_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.tour')),
            ],
            options={
                'verbose_name': 'Expédition',
                'verbose_name_plural': 'Expéditions',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.zone'),
        ),
    ]
