# Generated by Django 5.2.10 on 2026-01-24 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_driver_zone_typeservice_volume_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Enregistré'), ('TRANSIT', 'En transit'), ('SORTING', 'Centre de tri'), ('OUT_FOR_DELIVERY', 'En cours de livraison'), ('DELIVERED', 'Livré'), ('FAILED', 'Échec de livraison')], default='REGISTERED', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Enregistré'), ('TRANSIT', 'En transit'), ('SORTING', 'Centre de tri'), ('OUT_FOR_DELIVERY', 'En cours de livraison'), ('DELIVERED', 'Livré'), ('FAILED', 'Échec de livraison')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statuts',
                'ordering': ['-changed_at'],
            },
        ),
    ]
