# Generated by Django 5.2.10 on 2026-01-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0003_remove_tour_id_driver_remove_tour_id_vehicle_and_more'),
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='reclamations', to='expedition.shipment', verbose_name='Colis concernés'),
        ),
    ]
