# Generated by Django 6.0 on 2026-01-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('facturation', '0002_initial'),
        ('logistics', '0002_initial'),
        ('reclamation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Agent responsable'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='facturation.invoice', verbose_name='Facture concernée'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='reclamations', to='logistics.shipment', verbose_name='Colis concernés'),
        ),
        migrations.AddField(
            model_name='reclamationcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationcomment',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reclamation.reclamation'),
        ),
        migrations.AddField(
            model_name='reclamationdocument',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reclamation.reclamation'),
        ),
        migrations.AddField(
            model_name='reclamationdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationtask',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamation_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationtask',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reclamation.reclamation'),
        ),
    ]
