# Generated by Django 5.2.10 on 2026-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_driver_zone_typeservice_volume_rate_and_more'),
        ('reclamation', '0002_alter_reclamation_shipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='reclamations', to='logistics.shipment', verbose_name='Colis concernés'),
        ),
    ]
