# Generated by Django 6.0 on 2026-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_type',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], max_length=50),
        ),
    ]
